backend:
  name: git-gateway
  repo: "tomyueTW/happy-diary"
  branch: "master"
media_folder: "content/post/img"
locale: "zh_Hant"
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/post
    label: "Posts" # Used in the UI
    folder: "content/post" # The path to the folder where the documents are stored
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    format: 'toml-frontmatter'
    fields: # The fields for each document, usually in front matter
      - { label: '標題', name: 'title', widget: 'string' }
      - { label: '發布日期', name: 'date', widget: 'date' }
      - { label: '摘要', name: 'description', widget: 'string' }
      - { label: '內容', name: 'body', widget: 'markdown' }
      - { label: "標籤", name: "tags", widget: "list", required: false}
      - { label: "分類", name: "categories", widget: "list", required: false}
      - { label: "首圖", name: "image", widget: "image", required: false}
