backend:
  name: git-gateway
  repo: "tomyueTW/happy-diary"
  branch: "master"
media_folder: "static/img"
locale: "zh_Hant"
collections:
  - name: 'posts'
    label: '文章'
    folder: 'content/post'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: '標題', name: 'title', widget: 'string' }
      - { label: '發布日期', name: 'date', widget: 'date' }
      - { label: '摘要', name: 'description', widget: 'string' }
      - { label: '內容', name: 'body', widget: 'markdown' }
      - { label: "標籤", name: "tags", widget: "list", required: false}
      - { label: "分類", name: "categories", widget: "list", required: false}
      - { label: "首圖", name: "image", widget: "image"}
